language: python

python:
    - "2.7"

install:
  - pip install --upgrade pip
  - pip install --upgrade codecov
  - pip install --upgrade flake8

script: python utils.py

after_success:
  - codecov --env PY_VERSION

#=============================================================================
# Notifications
#=============================================================================
notifications:
  email:
    recipients: healther.astro@gmail.com
    on_success: change
    on_failure: always
